import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { plus_jakarta_sans } from "./ui/fonts";
import Footer from "./ui/footer";
import Header from "./ui/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${plus_jakarta_sans.className} text-sm`}>
        <div className="flex flex-col h-screen">
          <Providers>
            <Header />
            {children}
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
