import type { Metadata } from "next";
import "./globals.css";
import { plus_jakarta_sans } from "./ui/fonts";
import Footer from "./ui/footer";
import Header from "./ui/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${plus_jakarta_sans.className} text-sm`}>
        <div className="flex flex-col h-screen">
          <Header />
          <div className="bg-[#F6F7F9] flex-1 py-8 pb-16 px-16">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
